/* -------------------------------------------------------------------------- */
/*  Redfin results-page extraction (stabilization).                            */
/*                                                                            */
/*  Redfin's WAF (CloudFront) serves a 403 on individual /home/ detail pages   */
/*  to the automated browser, but the SEARCH RESULTS page renders fine and     */
/*  carries every listing's data on its cards. So we:                          */
/*    1. open redfin.com, resolve the market to a results URL via Redfin's own  */
/*       location-autocomplete (the resolver its search box uses), zip fallback;*/
/*    2. open that results page and read each card (address/price/beds/baths/   */
/*       sqft/photo/url) straight from the rendered DOM.                        */
/*  No detail-page visits, no CAPTCHA solving, no bot-protection bypass — just  */
/*  reading the public results page the same way a person would.               */
/*                                                                            */
/*  Per-card fields come from the visible results card (Redfin exposes no       */
/*  per-card JSON-LD/embedded data on the results page), so this is the         */
/*  appropriate place to read the DOM. Structured data is still preferred       */
/*  wherever it exists.                                                         */
/* -------------------------------------------------------------------------- */

import "server-only";
import type { BrowserContext, Page } from "playwright";
import { propertyKey } from "../../deals";
import { BLOCK_MARKERS, type StaticSiteConfig } from "../staticSite";
import {
  freshTracking,
  scoreConfidence,
  type ProviderDebug,
  type ProviderStatus,
  type ScanContext,
  type ScannedProperty,
  type ScanQuery,
} from "../types";

export type RedfinScanResult = {
  status: ProviderStatus;
  properties: ScannedProperty[];
  warnings: string[];
  debug: ProviderDebug;
};
import { dbg, dumpHtml } from "./debug";

const NAV_TIMEOUT_MS = 25_000;

export type RedfinCounters = {
  rendered: number; // cards seen
  converted: number; // cards -> ScannedProperty
  blocked: number;
  errored: number;
  failed: { url: string; title: string; missing: string[] }[];
};

export function newCounters(): RedfinCounters {
  return { rendered: 0, converted: 0, blocked: 0, errored: 0, failed: [] };
}

const CLOUDFRONT_BLOCK =
  /(the request could not be satisfied|generated by cloudfront|request blocked)/i;

/* -------------------------------- helpers --------------------------------- */

const toInt = (s: unknown): number | null => {
  const n = parseInt(String(s ?? "").replace(/[^0-9]/g, ""), 10);
  return Number.isFinite(n) && n > 0 ? n : null;
};
const toDec = (s: unknown): number | null => {
  const n = parseFloat(String(s ?? "").replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) && n > 0 ? n : null;
};

async function looksBlocked(page: Page): Promise<boolean> {
  const u = page.url().toLowerCase();
  if (/captcha|px-captcha|access-denied|\/blocked/.test(u)) return true;
  try {
    const head = (await page.content()).slice(0, 20_000);
    return BLOCK_MARKERS.test(head) || CLOUDFRONT_BLOCK.test(head);
  } catch {
    return false;
  }
}

async function autoScroll(page: Page): Promise<void> {
  try {
    await page.evaluate(async () => {
      await new Promise<void>((resolve) => {
        let total = 0;
        const step = 900;
        const timer = setInterval(() => {
          window.scrollBy(0, step);
          total += step;
          const atBottom =
            window.innerHeight + window.scrollY >= document.body.scrollHeight - 50;
          if (total >= 9000 || atBottom) {
            clearInterval(timer);
            resolve();
          }
        }, 200);
      });
    });
  } catch {
    /* non-fatal */
  }
}

function splitAddress(full: string): {
  address: string;
  city: string;
  state: string;
  zip: string;
} {
  const m = full.match(/^(.*?),\s*([^,]+),\s*([A-Za-z]{2})\s*(\d{5})/);
  if (m) {
    return {
      address: m[1].trim(),
      city: m[2].trim(),
      state: m[3].toUpperCase(),
      zip: m[4],
    };
  }
  return { address: full.trim(), city: "", state: "", zip: "" };
}

/* ---------------------------- market -> results URL ----------------------- */
/* Uses Redfin's own location-autocomplete (what the search box calls) so we    */
/* navigate to the canonical results page. Not a bypass — same-origin GET.      */

async function resolveResultsUrl(page: Page, market: string): Promise<string | null> {
  const api =
    "https://www.redfin.com/stingray/do/location-autocomplete?location=" +
    encodeURIComponent(market) +
    "&v=2&al=1&iss=false";
  const body = await page
    .evaluate(async (u) => {
      try {
        const r = await fetch(u, {
          headers: { accept: "application/json" },
          credentials: "include",
        });
        return await r.text();
      } catch {
        return "";
      }
    }, api)
    .catch(() => "");

  dbg("autocomplete", { len: body.length, head: body.slice(0, 300) });
  const isResultsPath = (u: string) =>
    /^\/(?:city|zipcode|county|neighborhood)\//i.test(u);

  if (body) {
    // Structured parse — prefer a city/zip/county results path.
    try {
      const json = JSON.parse(body.replace(/^\{\}&&/, ""));
      const sections = json?.payload?.sections ?? json?.sections ?? [];
      for (const section of sections) {
        for (const row of section?.rows ?? []) {
          if (typeof row?.url === "string" && isResultsPath(row.url)) {
            return "https://www.redfin.com" + row.url;
          }
        }
      }
    } catch {
      /* fall through to regex */
    }
    // Regex fallback — first results-type URL anywhere in the response.
    const m = body.match(
      /"url"\s*:\s*"((?:\\?\/)(?:city|zipcode|county|neighborhood)\/[^"]+)"/i,
    );
    if (m) return "https://www.redfin.com" + m[1].replace(/\\\//g, "/");
  }
  // Fallback: a 5-digit ZIP in the market string maps to a stable results URL.
  const zip = market.match(/\b(\d{5})\b/);
  if (zip) return `https://www.redfin.com/zipcode/${zip[1]}`;
  return null;
}

/* ----------------------------- card extraction ---------------------------- */

type RawCard = {
  url: string;
  address: string;
  price: string;
  beds: string;
  baths: string;
  sqft: string;
  photo: string;
};

async function readCards(page: Page): Promise<RawCard[]> {
  return page
    .$$eval(".HomeCardContainer", (cards) =>
      cards.map((card) => {
        const txt = (sel: string): string => {
          const el = card.querySelector(sel);
          return el ? (el.textContent || "").trim() : "";
        };
        const a = card.querySelector('a[href*="/home/"]') as HTMLAnchorElement | null;
        const img = card.querySelector("img") as HTMLImageElement | null;
        return {
          url: a ? a.href : "",
          address: txt(".bp-Homecard__Address"),
          price: txt(".bp-Homecard__Price--value"),
          beds: txt(".bp-Homecard__Stats--beds"),
          baths: txt(".bp-Homecard__Stats--baths"),
          sqft: txt(".bp-Homecard__Stats--sqft"),
          photo: img ? img.currentSrc || img.src : "",
        };
      }),
    )
    .catch(() => [] as RawCard[]);
}

function cardToScanned(
  c: RawCard,
  cfg: StaticSiteConfig,
  now: number,
): { sp: ScannedProperty | null; missing: string[] } {
  const { address, city, state, zip } = splitAddress(c.address);
  const price = toInt(c.price);
  const beds = toDec(c.beds);
  const baths = toDec(c.baths);
  const sqft = toInt(c.sqft);

  const missing: string[] = [];
  if (!address) missing.push("address");
  if (price == null) missing.push("price");
  if (beds == null) missing.push("beds");
  if (baths == null) missing.push("baths");
  if (sqft == null) missing.push("sqft");

  if (!address && price == null) return { sp: null, missing };

  const photoUrls =
    c.photo && /^https?:\/\//.test(c.photo) ? [c.photo.split("?")[0]] : [];

  return {
    sp: {
      propertyKey: propertyKey({ listingUrl: c.url, address, city, state, zip }),
      source: cfg.id,
      sourceLabel: cfg.label,
      listingUrl: c.url,
      address,
      city,
      state,
      zip,
      price,
      beds,
      baths,
      sqft,
      lotSize: "",
      yearBuilt: "",
      description: "",
      photoUrls,
      tracking: freshTracking(price, now),
      confidence: scoreConfidence({ address, price, beds, baths, sqft }),
      warnings: [],
    },
    missing,
  };
}

/* ------------------------------ main entry -------------------------------- */

export async function scanRedfinResults(
  context: BrowserContext,
  query: ScanQuery,
  cfg: StaticSiteConfig,
  now: number,
  counters: RedfinCounters,
  ctx: ScanContext,
): Promise<RedfinScanResult> {
  const warnings: string[] = [];
  const debug: ProviderDebug = {};
  const page = await context.newPage();
  try {
    // 1) Open Redfin so the autocomplete fetch is same-origin (cookies set).
    await page
      .goto("https://www.redfin.com/", { waitUntil: "domcontentloaded", timeout: NAV_TIMEOUT_MS })
      .catch(() => {});
    if (await looksBlocked(page)) {
      return { status: "blocked", properties: [], warnings: ["Redfin: blocked at homepage."], debug };
    }

    // 2) Resolve the market -> canonical results URL.
    const resultsUrl = await resolveResultsUrl(page, query.market);
    dbg("RESOLVE", { market: query.market, resultsUrl });
    if (!resultsUrl) {
      return {
        status: "blocked",
        properties: [],
        warnings: [
          `Redfin: couldn't resolve “${query.market}” — Redfin blocks its location lookup for automated browsers (no bypass attempted). Include a ZIP code in the market (e.g. “Sherman, TX 75090”) for reliable Redfin scans.`,
        ],
        debug,
      };
    }
    debug.searchUrl = resultsUrl;

    // 3) Open the results page.
    if (ctx.signal.aborted) {
      return { status: "ok", properties: [], warnings: ["Stopped early."], debug };
    }
    await page
      .goto(resultsUrl, { waitUntil: "domcontentloaded", timeout: NAV_TIMEOUT_MS })
      .catch(() => {});
    await page.waitForTimeout(2_000);
    await page
      .waitForSelector('.HomeCardContainer, [data-rf-test-name="mapHomeCard"]', { timeout: 10_000 })
      .catch(() => {});
    debug.searchUrl = page.url();
    if (await looksBlocked(page)) {
      const f = await dumpHtml("redfin", "results_blocked", await page.content().catch(() => ""));
      dbg("RESULTS blocked", { url: page.url(), dump: f });
      return {
        status: "blocked",
        properties: [],
        warnings: ["Redfin: results page blocked by bot protection (no bypass attempted)."],
        debug,
      };
    }
    await autoScroll(page);

    // 4) Read every card straight from the rendered results DOM.
    const dump = await dumpHtml("redfin", "results_cards", await page.content().catch(() => ""));
    const cards = await readCards(page);
    debug.cardsFound = cards.length;
    dbg("CARDS", {
      resultsUrl: page.url(),
      cards: cards.length,
      sample: cards.slice(0, 3),
      dump,
    });

    const byKey = new Map<string, ScannedProperty>();
    for (const c of cards) {
      if (byKey.size >= query.maxResults) break;
      counters.rendered++;
      const { sp, missing } = cardToScanned(c, cfg, now);
      if (sp && sp.propertyKey) {
        if (!byKey.has(sp.propertyKey)) {
          byKey.set(sp.propertyKey, sp);
          counters.converted++;
        }
      } else {
        counters.failed.push({ url: c.url, title: c.address, missing });
      }
    }

    const properties = Array.from(byKey.values());
    debug.cardsConverted = properties.length;
    if (properties.length === 0) {
      return {
        status: "empty",
        properties: [],
        warnings: [...warnings, "Redfin: results page had no parseable listing cards."],
        debug,
      };
    }
    return { status: "ok", properties, warnings, debug };
  } catch (e) {
    counters.errored++;
    dbg("scanRedfinResults error", String(e).slice(0, 200));
    return { status: "error", properties: [], warnings: ["Redfin: scan failed unexpectedly."], debug };
  } finally {
    await page.close().catch(() => {});
  }
}
